name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run tests
        run: |
          mkdir -p build
          g++ -std=c++17 -g test/unit_tests.cpp src/*.cpp -o build/test.out -I${GITHUB_WORKSPACE}/include -I${GITHUB_WORKSPACE}/test
          ./build/test.out --no-breaks --success --out=test-results.xml --reporters=junit
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: test-results.xml
          reporter: java-junit
      - name: Autograding
        uses: education/autograding@v1 
